// Package model contains shared type aliases and WebSocket event types.
//
// Data structs (Game, Player, etc.) are generated by sqlc in db/gen/.
// This package holds only the typed string enums that sqlc uses via
// column overrides, plus the WebSocket event/payload types in ws.go.
package model

// ── Game Phase ──────────────────────────────────────────────────────────────

type GamePhase string

const (
	PhaseLobby     GamePhase = "lobby"
	PhasePrologue  GamePhase = "prologue"
	PhaseMainEvent GamePhase = "main_event"
	PhaseShakeUp   GamePhase = "shake_up"
	PhaseEnded     GamePhase = "ended"
)

// ── Tone Topic Status ───────────────────────────────────────────────────────

type ToneTopicStatus string

const (
	ToneDefault     ToneTopicStatus = "default"
	ToneInclude     ToneTopicStatus = "include"
	ToneAvoidDetail ToneTopicStatus = "avoid_detail"
	ToneNever       ToneTopicStatus = "never"
)

// ── Ranking Category ────────────────────────────────────────────────────────

type RankingCategory string

const (
	CategoryPower     RankingCategory = "power"
	CategoryKnowledge RankingCategory = "knowledge"
	CategoryEsteem    RankingCategory = "esteem"
)

// ── Asset Type ──────────────────────────────────────────────────────────────

type AssetType string

const (
	AssetPeer     AssetType = "peer"
	AssetHolding  AssetType = "holding"
	AssetArtifact AssetType = "artifact"
	AssetResource AssetType = "resource"
)

// ── Plan Type ───────────────────────────────────────────────────────────────

type PlanType string

const (
	PlanMakeDemands         PlanType = "make_demands"
	PlanProposeDecree       PlanType = "propose_decree"
	PlanExchangeCourtiers   PlanType = "exchange_courtiers"
	PlanMakeWar             PlanType = "make_war"
	PlanMakeIntroductions   PlanType = "make_introductions"
	PlanSeekAnswers         PlanType = "seek_answers"
	PlanChronicleHistories  PlanType = "chronicle_histories"
	PlanClandestinelyLiaise PlanType = "clandestinely_liaise"
	PlanSpreadPropaganda    PlanType = "spread_propaganda"
	PlanSpreadRumors        PlanType = "spread_rumors"
	PlanProposeDuel         PlanType = "propose_duel"
	PlanHostFestivity       PlanType = "host_festivity"
)

// ── Scene Time Elapsed ──────────────────────────────────────────────────────

// TimeElapsed describes how much in-fiction time has passed between this
// scene and the previous one (or whether it's a flashback / simultaneous).
type TimeElapsed string

const (
	TimeMoments      TimeElapsed = "moments"
	TimeHours        TimeElapsed = "hours"
	TimeDays         TimeElapsed = "days"
	TimeWeeks        TimeElapsed = "weeks"
	TimeFlashback    TimeElapsed = "flashback"
	TimeSimultaneous TimeElapsed = "simultaneous"
)

// ── Scene Kind ──────────────────────────────────────────────────────────────

// SceneKind distinguishes a focus player's turn-scene (location/time setup,
// SCENES_PLAN.md) from a plan-scene (adr/CHAT_OVERHAUL_PLAN.md Phase 5): a
// roleplay container opened for the duration of a roleplay-heavy plan's
// resolution, with no location/time setup step. At most one scene of either
// kind is active per game at a time (scenes_one_active_per_game).
type SceneKind string

const (
	SceneKindTurn SceneKind = "turn"
	SceneKindPlan SceneKind = "plan"
)

// ── Plan Status ─────────────────────────────────────────────────────────────

type PlanStatus string

const (
	PlanPending   PlanStatus = "pending"
	PlanResolving PlanStatus = "resolving"
	PlanResolved  PlanStatus = "resolved"
	PlanCancelled PlanStatus = "cancelled"
)

// ── Feedback Kind ───────────────────────────────────────────────────────────

// FeedbackKind distinguishes the two intakes that share the
// feedback_submissions table (adr/FEEDBACK_AND_RESET_PLAN.md): a login-gated
// feedback form and a logged-out "locked out?" password-reset request.
type FeedbackKind string

const (
	FeedbackKindFeedback     FeedbackKind = "feedback"
	FeedbackKindResetRequest FeedbackKind = "reset_request"
)
