// Package db contains migration logic and helper functions that don't map
// to single SQL queries (and therefore can't be generated by sqlc).
//
// All single-query database access is generated in db/gen/ (package dbgen).
package db

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"math/big"

	dbgen "uneasy/db/gen"
	"uneasy/model"
)

const (
	joinCodeLength   = 6
	cookieTokenBytes = 32 // 256-bit token for cryptographic security
)

// NewCookieToken generates a cryptographically random URL-safe token for use
// as a player's browser cookie.
func NewCookieToken() (string, error) {
	b := make([]byte, cookieTokenBytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("db: generate cookie token: %w", err)
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

// joinCodeAlphabet excludes ambiguous characters (0/O, 1/I/L) so codes are
// easy to read and share verbally.
const joinCodeAlphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"

// GenerateJoinCode returns a random 6-character join code.
func GenerateJoinCode() (string, error) {
	b := make([]byte, joinCodeLength)
	for i := range b {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(joinCodeAlphabet))))
		if err != nil {
			return "", fmt.Errorf("db: generate join code: %w", err)
		}
		b[i] = joinCodeAlphabet[n.Int64()]
	}
	return string(b), nil
}

// SeedDefaultToneTopics inserts the standard topics from the Uneasy rulebook.
// This is a multi-row INSERT loop that can't be expressed as a single sqlc query.
func SeedDefaultToneTopics(ctx context.Context, q *dbgen.Queries, gameID int64) error {
	topics := []string{
		"Torture",
		"Sex",
		"Romance",
		"Incest",
		"Execution",
		"Blood",
		"Child marriage",
		"Gore",
		"Arranged marriage",
		"Murder",
		"Plague",
		"Distressing medical practices",
		"Crusades",
		"Real-world religions",
		"Catholicism",
		"Slavery",
		"Classism",
		"Xenophobia",
		"Homophobia",
		"Cruelty",
		"Racism",
		"Proto-capitalism",
		"Holy war",
		"Capitalism",
		"Transphobia",
		"Verbal abuse",
		"Physical abuse",
		"Sexual abuse",
		"Modern day",
		"Weird beasts",
		"Emotional abuse",
		"Misogyny",
		"Corporal punishment",
		"Alcohol",
		"Magic",
		"Historical misogyny",
		"Patriarchy",
		"Dragons child abuse",
		"Science fiction",
		"Casteism",
	}
	for _, t := range topics {
		if err := q.SeedToneTopic(ctx, dbgen.SeedToneTopicParams{
			GameID: gameID,
			Topic:  t,
			Status: model.ToneDefault,
		}); err != nil {
			return fmt.Errorf("db: seed tone topic %q: %w", t, err)
		}
	}
	return nil
}
